### ISSUE TITLE
Release unchanging versions

### ISSUE THREAD

**Issue by l0b0** [linz/action-typescript#1]
Using the branch name as the version ID is confusing, non-standard, and means it's not possible to pin a `uses` directive to a (hopefully non-moving) tag. Basically, if `linz/action-typescript@v1` changes in some way, this could break dependent projects in ways which are hard to debug. It would be good if this project used the standard release mechanism (or just tags rather than branches) instead.

**Comment by blacha** [comment]
When this was made, the standard way of making actions was to use branches not tags, tags can and will move if you really want to pin something then you need to use the commit hash.

The whole point of this github action was update all github actions versions to the latest LTS nodejs version, but it now appears dependabot will automatically upgrade things for us, so this is less of a problem.
